# Generated by Django 4.2.8 on 2023-12-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='profile',
            new_name='user',
        ),
    ]
